version: "2.3" # the only version where 'runtime' option is supported
services:
  stable_diffusion:
    tty: true        # docker run -t
    shm_size: 128gb
    build: .
    image: webui-docker
    container_name: sd_webui
    volumes:
      - .:/stable-diffusion-webui
    ports:
      - 7860:7860 # stable diffusion ui
    deploy: ## important
      resources:
        reservations:
          devices:
            - capabilities: [gpu]